version: "3.8"
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: gitlab-runner
    volumes:
      - "./gitlab-runner:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: 'host'

